### PR TITLE
needed a new branch to do a PR

### PR DESCRIPTION
**Pull request by orthagonal**

### CODE REVIEW

**Comment by orthagonal** [comment]
Am going to prettify the README a little bit

**Comment by jgallen23** [comment]
y u no es6?

**Comment by jgallen23** [comment]
Feedback:
- [ ] es6 - please lint.  (const, template strings, arrow functions)
- [ ] no need for lib folder.  only needed if multiple files
- [ ] don't need `options.router.redirectTrailingSlash`, just have `options.method`.
- [ ] throw error if `options.method` isn't set
- [ ] remove router key for logging. just do `options.verbose` to enable logging
- [ ] lots of `server.ext('onRequest', function (request, reply) {`  put that on the outside and to the if statement inside
- [ ] does the redirect work with query params?
- [ ] what happens for requests other than GETs?
- [ ] server.log needs tags.  use [hapi-trailing-slash, redirect]
- [ ] what is lodash for?
- [ ] for tests, set up nested experiment for append, remove, ignore and then put a before to set up server so each test just does a server.inject lots of duplicate code, hard to read tests

**Comment by orthagonal** [comment]
@jgallen23  hapi-trailing-slash should be ready for review now

**Comment by orthagonal** [comment]
- es5 -> es6
- lint corrections
- split tests into 3 files, one for each of 'remove', 'smart', 'append'
- 'smart' now does an internal reroute using setUrl+continue() instead of redirect
- redirect done by 'remove'/'append' preserve the original query and url params in header.location

**Pull request merged**
